services:
  # --- BACKEND (FastAPI) ---
  - type: web
    name: 8cubeAPI
    env: python
    plan: starter
    buildCommand: pip install -r 8cube_API/requirements.txt
    startCommand: uvicorn 8cube_API.api:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PORT
        value: 8000

  # --- FRONTEND (Streamlit) ---
  - type: web
    name: MouseExplorer
    env: python
    plan: free
    buildCommand: pip install -r 8cube_API/frontend/requirements.txt
    startCommand: streamlit run 8cube_API/frontend/frontend_app.py --server.port 8501 --server.address 0.0.0.0
    envVars:
      - key: PORT
        value: 8501
