services:
  - type: web
<<<<<<< HEAD
    name: 8cubeDB
    env: python
    plan: starter
    buildCommand: pip install -r 8cube_API/requirements.txt
    startCommand: uvicorn 8cube_API.api:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PORT
        value: 8000
